# Generated by Django 4.1 on 2022-09-07 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_short', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='active_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 18, 17, 22, 552605)),
        ),
        migrations.AddField(
            model_name='shortener',
            name='status',
            field=models.CharField(choices=[('enable', 'ENABLE'), ('disable', 'DISABLE')], default='enable', max_length=20),
        ),
    ]
