# Generated by Django 4.1.1 on 2022-09-08 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_short', '0002_shortener_active_time_shortener_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='active_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 10, 14, 23, 959774)),
        ),
    ]
