# Generated by Django 4.1 on 2022-09-09 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_short', '0004_alter_shortener_active_time_alter_shortener_long_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='active_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 17, 10, 47, 216198)),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='long_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
